# Site Settings
# Do not use trailing slash (i.e. "/Sample"). For skipping base URL, leave empty quotes ("")
baseurl: "" # "/Grape-Academic-Theme"

# Features Setting
# Turn subpages on or off
publications: True
presentations: True
education: True
blog: False

# Language of the website
lang: en

# Search engine optimization settings
title: Shuo SUN's Portfolio
tagline: Shuo SUN's Portfolio
description: Ph.D. Candidate & Robotics Engineer @ Advanced Robotics Centre (ARC), National University of Singapore (NUS)
author: Shuo SUN (SS47816)
twitter:
  username: SS47816
  card: Ph.D. Candidate & Robotics Engineer @ Advanced Robotics Centre (ARC), National University of Singapore (NUS)
logo: /assets/img/avatar.png
social:
  name: Shuo SUN
  links:
    - https://github.com/ss47816
locale: en_GB

# Page Settings
theme_settings:
  title: Grape Academic Theme
  education_title: EDUCATION
  experience_title: WORK EXPERIENCE
  interests_title: SKILLS
  awards_title: LICENSES & CERTIFICATIONS
  skills_title: SKILLS
  projects_title: HIGHLIGHTED PROJECTS
  recentpubs_title: RECENT PUBLICATIONS

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Settings
sass:
  sass_dir: _sass
  style: :compressed
plugins: ['jekyll-paginate', 'jekyll/scholar', 'jekyll-seo-tag']
bootstrap:
  assets: true

# Bibliography settings
scholar:
  bibliography: publications.bib
  bibliography_template: pubstemplate
  style: ieee
  locale: en
  last_name: Sun
  first_name: [Shuo, S.]
  sort_by: year,month
  order: descending,ascending

filtered_bibtex_keywords: [abbr, abstract, arxiv, bibtex_show, html, pdf, selected, supp, blog, code, poster, slides, website] # Filter out certain bibtex entry keywords used internally from the bib output

academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="
fontawesome:
  version: "5.15.4"
  integrity: "sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
